title: raskat-detector
optionalCategoryIndex: true
supportedLanguages: []
properties: []
logo: raSkat.svg
logo_dark: raSkat.svg
relatedLinks:
  - url: https://t.me/raSkat_team
    title: Telegram-канал
    icon: mail-question